[build]
builder = "NIXPACKS"
buildCommand = "cd backend && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "cd backend && java -jar target/*.jar"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[database]
name = "weddingyou"