[build]
builder = "NIXPACKS"
buildCommand = "cd backend && chmod +x mvnw && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "cd backend && java -jar target/*.jar"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"

[database]
name = "weddingyou"